//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.SrvcReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrvcReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCustInfo", ReplyAction="http://tempuri.org/IService1/GetAllCustInfoResponse")]
        string GetAllCustInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCustInfo", ReplyAction="http://tempuri.org/IService1/GetAllCustInfoResponse")]
        System.Threading.Tasks.Task<string> GetAllCustInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTest", ReplyAction="http://tempuri.org/IService1/GetTestResponse")]
        string GetTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTest", ReplyAction="http://tempuri.org/IService1/GetTestResponse")]
        System.Threading.Tasks.Task<string> GetTestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostCustInfo", ReplyAction="http://tempuri.org/IService1/PostCustInfoResponse")]
        void PostCustInfo(string user, string Company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostCustInfo", ReplyAction="http://tempuri.org/IService1/PostCustInfoResponse")]
        System.Threading.Tasks.Task PostCustInfoAsync(string user, string Company);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.SrvcReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.SrvcReference.IService1>, Client.SrvcReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAllCustInfo() {
            return base.Channel.GetAllCustInfo();
        }
        
        public System.Threading.Tasks.Task<string> GetAllCustInfoAsync() {
            return base.Channel.GetAllCustInfoAsync();
        }
        
        public string GetTest() {
            return base.Channel.GetTest();
        }
        
        public System.Threading.Tasks.Task<string> GetTestAsync() {
            return base.Channel.GetTestAsync();
        }
        
        public void PostCustInfo(string user, string Company) {
            base.Channel.PostCustInfo(user, Company);
        }
        
        public System.Threading.Tasks.Task PostCustInfoAsync(string user, string Company) {
            return base.Channel.PostCustInfoAsync(user, Company);
        }
    }
}
